name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file WebApp/Dockerfile --tag my-image-name:$(date +%s)
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: WebApp/Dockerfile
        repository: xgsince/corewebapplication1
        tag_with_ref: true
    #- name: SSH Remote Commands
     # uses: appleboy/ssh-action@v0.1.1
